### ISSUE TITLE
Get cars images and provide overlay built of cars status

### ISSUE THREAD

**Issue by tillsteinbach** [tillsteinbach/WeConnect-python#10]
Get the nice pictures displaying the car in its real configuration and also calculate the schematic image from the cars status (door state, windows, lights, etc.) currently only useful for cars that are not an ID as the IDs don't provide status for doors, etc.

Needs to be thought through what a good user interface e.g. for the CLI is. Probably it only makes sense to allow to save the images

**Comment by tillsteinbach** [comment]
<img width="1109" alt="Bildschirmfoto 2021-07-04 um 22 09 14" src="https://user-images.githubusercontent.com/3825852/124398174-a313cb80-dd14-11eb-929e-ba36dda528fe.png">
Even nice for CLI :)

**Comment by mitch-dc** [comment]
How do i create/save this image? :)

**Comment by mitch-dc** [comment]
De combined png images if that's possible

**Comment by tillsteinbach** [comment]
There is an example that saves everything here: https://github.com/tillsteinbach/WeConnect-python/blob/main/examples/savePictures.py
Is that what you are looking for?
