### ISSUE TITLE
Remaining Charging Time

### ISSUE THREAD

**Issue by NikolasRupp** [tillsteinbach/WeConnect-python#101]
Hi, 

in other Methods to access the Info you also get access to ["charging"]["chargingStatus"]["remainingChargingTimeToComplete_min"]. Is it somehow possible to access that here too? 

Thanks for your help

**Comment by tillsteinbach** [comment]
Yes, see here: https://github.com/tillsteinbach/WeConnect-python/blob/cb414ad3adccd821fe457c74523b80e8b6c182e5/weconnect/elements/charging_status.py#L19

**Comment by NikolasRupp** [comment]
Thank you. I must have overlooked that.
