### ISSUE TITLE
Detected integration that called async_setup_platforms instead of awaiting async_forward_entry_setups

### ISSUE THREAD

**Issue by viking2010** [tillsteinbach/WeConnect-python#102]
**Describe the bug**
After updating HA to Home Assistant 2023.2.2, I get the error "Detected integration that called async_setup_platforms instead of awaiting async_forward_entry_setups" in the logs:

**To Reproduce**
Steps to reproduce the behaviour:
Update to HA v2023.2.2
Check the logs

**Expected behaviour**
N/A

**Screenshots**
![image](https://user-images.githubusercontent.com/100141279/217642803-4b3b58e4-667c-4881-b295-1682a6f17b96.png)

**Logs**
`Logger: homeassistant.helpers.frame
Source: helpers/frame.py:77
First occurred: 20:19:58 (1 occurrences)
Last logged: 20:19:58

Detected integration that called async_setup_platforms instead of awaiting async_forward_entry_setups; this will fail in version 2023.3. Please report issue to the custom integration author for volkswagen_we_connect_id using this method at custom_components/volkswagen_we_connect_id/__init__.py, line 92: hass.config_entries.async_setup_platforms(entry, PLATFORMS)`

HA Version Info:
Home Assistant 2023.2.2
Supervisor 2023.01.1
Operating System 9.5
Frontend 20230202.0 - latest

**Additional context**
This is based on the latest update to We Connect ID (v0.1.3) integration in HACS, which has then had the files provided from this repo, to allow it to work with the Cupra Born. 

I tried to alter line 92 in the custom_components/volkswagen_we_connect_id/__init__.py file from:

`hass.config_entries.async_setup_platforms(entry, PLATFORMS)`

to...

`hass.config_entries.async_forward_entry_setups(entry, PLATFORMS)`

...but clearly Python isn't my strong point and just made all the entities unavailable. It might be in the right format, but it could be there's something else in the file that also needs altering.

Just ask if there's any more info you need!

**Comment by tillsteinbach** [comment]
Sorry, I think you are wrong here. You probably wanted to report your issue here: https://github.com/mitch-dc/volkswagen_we_connect_id

**Comment by viking2010** [comment]
My apologies, I'll raise with the original integration. Just wasn't sure if it was something that was added from this integration that would have caused this issue or the original one. Thank you

**Comment by tillsteinbach** [comment]
No problem!
