### ISSUE TITLE
"Unknown attribute targetSOC_pct" after T&C update

### ISSUE THREAD

**Issue by towe96** [tillsteinbach/WeConnect-python#105]
**Describe the bug**
Since having had to confirm new T&Cs, error / warning lines keep coming up in my script after the "Update" step of it, even when the attributes are not used in the code.

**To Reproduce**
- Run the example file "[climatization.py](https://github.com/tillsteinbach/WeConnect-python/blob/main/examples/climatization.py)" with correct credentials
- The warning messages are shown after the "Update" step

**Expected behavior**
No error / warning message after the "Update" step

**Screenshots**
![screenshot](https://user-images.githubusercontent.com/43667506/218950394-6059b39a-e421-4019-a207-26d5aada2c85.png)

**Logs**
 - OS: Windows 10
 - Version used: 0.51.1, Python 3.11

**Comment by tillsteinbach** [comment]
Attribute was added and is now in testing

**Comment by towe96** [comment]
Warning is gone in my script now (0.52.0) and the new attribute shows up in weconnect-cli and is readable.

**Comment by tillsteinbach** [comment]
Perfect, thanks for reporting back!
