### ISSUE TITLE
Login suddenly not possible anymore 

### ISSUE THREAD

**Issue by TobiasIW** [tillsteinbach/WeConnect-python#106]
Hi,
I have built a smart charging SW using Info from your library, which is awesome! Since ~2 days, I get the fault `OAUTH sc2:fal not present, cannot refresh`, leading to a crash in the SW.
Do you know, what could be the reason? Access via app is still possible.
Regards,
Tobias

**Comment by tillsteinbach** [comment]
can you quickly try if you get data if you use [WeConnect-cli](https://github.com/tillsteinbach/WeConnect-cli)? And did you accept the new WeConnect terms and conditions already?

**Comment by TobiasIW** [comment]
It worked after accepting T&Cs on the website. Didn't see it in the app, so I thought I had done it already. Thank you for the quick help!
