### ISSUE TITLE
Cannot login

### ISSUE THREAD

**Issue by Maxwell86** [tillsteinbach/WeConnect-python#112]
**Describe the bug**
When calling "weConnect.login()", it gives the error "No user id provided"

**Additional context**
Everything was running well until one week ago. Initially, the login problems seemed to be resolved thanks to the update to 0.54.1.
However, since a couple of days, the error "No user id provided" started to appear.

What could be the issue?
Thanks in advance!

**Comment by tillsteinbach** [comment]
You need to login at myvolkswagen and accept the terms and conditions

**Comment by Maxwell86** [comment]
Indeed, logging in at myvolkswagen again did the trick.
Thanks!
