### ISSUE TITLE
Problem refreshing token

### ISSUE THREAD

**Issue by 0rsa** [tillsteinbach/WeConnect-python#117]
Hello,
Since yesterday, I'm not able to refresh token

`2023-03-16T17:20:50+0100:CRITICAL:There was a problem when communicating with WeConnect: Status Code from WeConnect while refreshing tokens was: 400`

Maybe my account server is down again.
Are you expecting the same issue?

Thank you

**Comment by tillsteinbach** [comment]
I had this one time yesterday, but now everything is fine again. But I heard that the terms and conditions changed again. So maybe this is the problem?

**Comment by tillsteinbach** [comment]
Just to confirm: you are on the latest version?

**Comment by 0rsa** [comment]
Yes I did the update (stable version) just before to post my issue
Successfully installed weconnect-0.54.2

**Comment by 0rsa** [comment]
No, I will have a check on that, thank you

An interesting thing or not, I tried to connect to the VW shop and I'm getting this error:

`The We Connect web shop will be back soon.
We are working to improve your customer experience of the web shop. The page will be available again shortly. In the meantime, you can use the in-car shop in your infotainment system.`

Maybe there is not link between my issue and that but it is for notice.

**Comment by 0rsa** [comment]
Ok we are going forward, this time I got this:

`2023-03-16T17:37:16+0100:CRITICAL:There was a problem when authenticating with WeConnect: You have to login at myvolkswagen.de and accept the terms and conditions`

I'm not using the portal .de, I will try to log in on this one

**Comment by 0rsa** [comment]
Not better with the .de portal
When you go to the "Profile" section, do you have "Privacy settings and consents"?
From my side, I have none: You have not currently given any additional consent.

**Comment by 0rsa** [comment]
That was my idea too, I didn't use the app for a long time
I'm updating it

**Comment by 0rsa** [comment]
ok you are brilliant
I had to log out and log in again to have new terms and accept it.
If you launch the app and you are already connected, the new terms don't display.

Your python library works again, thank you!
