### ISSUE TITLE
bug  domain/vehicleLights/lightsStatus - unsupported status

### ISSUE THREAD

**Issue by psteinrueck** [tillsteinbach/WeConnect-python#118]
When retrieving domains with weconnect.py after login and update the - non fatal - error message is prompted

/vehicles/WVGZZZE2ZMP015321/domains/vehicleLights/lightsStatus/lights/right/status: An unsupported status: invalid was provided, known values are [on, off, unknown open state] please report this as a bug
/vehicles/WVGZZZE2ZMP015321/domains/vehicleLights/lightsStatus/lights/left/status: An unsupported status: invalid was provided, known values are [on, off, unknown open state] please report this as a bug

WVGZZZE2ZMP015321 is an ID.4 with SW 3.0.

**Comment by tillsteinbach** [comment]
0.55.0 was released
