### ISSUE TITLE
Parking position

### ISSUE THREAD

**Issue by Maxwell86** [tillsteinbach/WeConnect-python#139]
Dear,

I would like to retrieve the data of the parking position of my car.
(In the WeConnect app, it is correctly displayed on the map.)

However, I get: 
         [parkingPosition] disabling: True (expires 2053-08-11T23:59:59+00:00)
While I was hoping to receive the latitude and the longitude.

I wonder, did I do something wrong or am I forgetting to adjust some setting?
Or is this behavior normal (because this feature is not implemented yet)?

Thanks in advance!

Best regards,
Maxwell86

**Comment by Maxwell86** [comment]
Sorry, the data is simply under [parking][parkingPosition].

My apologies,
Maxwell86

**Comment by tillsteinbach** [comment]
No problem, glad you found everything!
