### ISSUE TITLE
An unsupported batteryPowerLevel: emergency was provided

### ISSUE THREAD

**Issue by johanflikweert** [tillsteinbach/WeConnect-python#140]
**Describe the bug**
Since yesterday I got the following log message:
`/vehicles/WVG{{anonymized}}/domains/readiness/readinessStatus/connectionState/batteryPowerLevel: An unsupported batteryPowerLevel: emergency was provided, known values are [comfort, off, unknown battery power level] please report this as a bug`

Also the parking is now empty, so I don't see where my car is :(

**To Reproduce**
1. Run the update example flow

Version used: first I used 0.55.1, but also 0.57.0 has this result.

**Comment by tillsteinbach** [comment]
I added the "emergency" power level for the next release, but I believe that the missing parking position is due to something else. Do you see the parking position in the Volkswagen App?

**Comment by johanflikweert** [comment]
Thank you.
Ah, that's unfortunate. For me, the issues are linked: either I got this log and no parking position, or a couple of hours later, both issues are resolved. Yes, I do see the parking position in the app.

**Comment by johanflikweert** [comment]
Yes, the VW app doesn't seem affected and still knows the location.

**Comment by johanflikweert** [comment]
Thanks for adding this unknown batteryPowerLevel. The other issues were due to too many logins.
