### ISSUE TITLE
Unknown attribute averageAuxConsumption/averageRecuperation

### ISSUE THREAD

**Issue by hanjuq** [tillsteinbach/WeConnect-python#141]
Hi Till,

after running weconnect-mqtt I tried to go a bit more to the root and made a first step with weconnect-python.
I started alVehicles.py and beside many correct and well formatted data I got this:

/vehicles/... /trips/shortTerm: Unknown attribute averageAuxConsumption with value 2.9
/vehicles/... /trips/shortTerm: Unknown attribute averageRecuperation with value 4.2
/vehicles/... /trips/longTerm: Unknown attribute averageAuxConsumption with value 2.5
/vehicles/... /trips/longTerm: Unknown attribute averageRecuperation with value 5.1

Very interesting because this were the only topics that I missed in weconnect-mqtt.

The original volkswagen app delivers this values and the robinostlund ha integration did it also.

I use a 2021 e-up!

Jürgen

**Comment by tillsteinbach** [comment]
Great, this is a brand new update in the backend. I will try to add those asap and make a new release.

**Comment by hanjuq** [comment]
Till, thanks for working well 0.58.0!!
