### ISSUE TITLE
Trip data are not updated

### ISSUE THREAD

**Issue by gilder0** [tillsteinbach/WeConnect-python#144]
**Describe the bug**
I try to use last shortTerm Trip Data with Home Assistant and initialy everything looks OK, but after a while, i've noticed that trips data were not updated.
After restarting Home Assistant trips data was retrieved correctly.

It seems, like the trip data is cached and not update.

**To Reproduce**

**Expected behavior**

**Screenshots**

**Logs**

**Additional context**

**Comment by hanjuq** [comment]
Ahh.. I also had an idea that something is wrong. So I compared with trip data from App. Result: my weconnect-python also shows old trip data while 3 newer sets are existing. After restart of my self made docker container it was OK. My container doesn't store any persistant data.
