### ISSUE TITLE
Not sure if it's a bug, but I can't find a way to set the value of targetSOC_pct.  Setting the value in vehicle.domains["charging"]["chargingSettings"].targetSOC_pct does not seem to have any effect, and I can't find anything in vehicle.controls.  Is there any way to set it?  Otherwise, a great library which has been extremely useful - thank you!

### ISSUE THREAD

**Issue by brian-rayner** [tillsteinbach/WeConnect-python#146]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Logs**
IF applicable logs that show the problem. Please take care to remove any confidential data from the logs (e.g. your vehicles VIN number, usernames or passwords)

 - OS: [e.g. Windows, Linux, MacOS, ...]
 - Version used [e.g. 0.6.2]

**Additional context**

**Comment by tillsteinbach** [comment]
hmmm, this should work. What type of car is it?

**Comment by brian-rayner** [comment]
It’s a VW ID.3 2021 model.  

 

On further investigation, if I immediately read back the value of vehicle.domains["charging"]["chargingSettings"].targetSOC_pct after the update, the change is reflected in the data.  However, it isn’t reflected in the vehicle itself and when I do a subsequent call to weConnect.update() it has reverted to the original value. Am I missing a step to commit the change to the vehicle?

**Comment by brian-rayner** [comment]
OK, it's working now.  It appears that the car will only accept increments of 10%, so was not allowing me to set it to 85%.  When I set it to 90% all was well!
