### ISSUE TITLE
consentURL not printed

### ISSUE THREAD

**Issue by monojk** [tillsteinbach/WeConnect-python#15]
The print format seems to be wrong. I get this message:
CRITICAL:weconnect-cli:There was a problem when authenticating with WeConnect: It seems like you need to accept the terms and conditions for the WeConnect ID service. Try to visit the URL "{consentURL}" or log into the WeConnect ID smartphone app

**Comment by tillsteinbach** [comment]
Yes, it was a f-string before but got messed up when fixing static linter issues. I'll plan to fix it tomorrow.

Suggested Workaround is installing the WeConnect ID App and accept the terms there until I have it fixed.

**Comment by tillsteinbach** [comment]
Should be fixed in WeConnect-python 0.20.3 and consequently fixed in WeConnect-cli 0.14.5 and WeConnect-mqtt 0.14.6
