### ISSUE TITLE
Small example for using with python

### ISSUE THREAD

**Issue by MyGitIT** [tillsteinbach/WeConnect-python#16]
Do you have a small example how to use your great work with python?

**Comment by tillsteinbach** [comment]
That is on my list just after proper documentation of the code 😐 
For now you could have a look in this: https://github.com/tillsteinbach/WeConnect-cli/blob/main/weconnect_cli/weconnect_cli.py or that https://github.com/tillsteinbach/WeConnect-mqtt/blob/main/weconnect_mqtt/weconnect_mqtt.py

Or this one: https://github.com/tillsteinbach/VWsFriend

Sorry, I know it sucks having an API without examples.

**Comment by tillsteinbach** [comment]
There are now some examples: https://github.com/tillsteinbach/WeConnect-python/tree/main/examples
