### ISSUE TITLE
 Unknown attributes

### ISSUE THREAD

**Issue by legantois** [tillsteinbach/WeConnect-python#162]
Semmes there has been an update with new attributes (my auto is ID.4 - and i use we connect from home assistant)

Unknown attribute targetTime with value 07:00
Unknown attribute repetitionDays with value ['monday', 'tuesday', 'wednesday', 'thursday', 'friday']
Unknown attribute targetDateTime with value 2023-06-30T23:00:00Z
Unknown attribute nextChargingTimer with value {'id': 0, 'targetSOCreachable': 'invalid'}
Unknown attribute nextChargingTimer with value {'id': 0, 'targetSOCreachable': 'invalid'}
Unknown attribute targetTime with value 07:00
Unknown attribute repetitionDays with value ['monday', 'tuesday', 'wednesday', 'thursday', 'friday']
Unknown attribute targetDateTime with value 2023-06-30T23:00:00Z

**Comment by henel321** [comment]
Any news on this? It's not breaking anything that I can see but causing a lot of logging noise. 

Thanks for you awesome work on this library!

**Comment by redlefloh** [comment]
Hi @tillsteinbach, did you get a chance to look at this? Like others I also get a lot of logging noise when using [https://github.com/mitch-dc/volkswagen_we_connect_id](https://github.com/mitch-dc/volkswagen_we_connect_id) in home assistant so it would be great if you could fix the naming issues with the attributes. 

Thanks a lot and thanks for the amazing work on this library, works really great!

**Comment by legantois** [comment]
I stopped using this integration and i switched to https://github.com/robinostlund/homeassistant-volkswagencarnet
it now supports IDs

All working well since there

May be better to collaborate on one single integration ?

**Comment by tillsteinbach** [comment]
fixed in 0.60.4
