### ISSUE TITLE
Skript mit SEAT/CUPRA nutzbar

### ISSUE THREAD

**Issue by xerion3800** [tillsteinbach/WeConnect-python#17]
Ist das Skript auch mit SEAT bzw. CUPRA nutzbar und wenn ja was muss ich anpassen?

**Comment by tillsteinbach** [comment]
@xerion3800 Die My Cupra App ist jetzt verfügbar, kannst du checken ob dein vor Gen 4 Fahrzeug dort angezeigt wird?

**Comment by xerion3800** [comment]
So wie ich das aus der App entnehme scheint es in erster Linie wohl nur den Cupra Born zu betreffen. Ich hatte es trotzdem mal versucht aber leider ohne Erfolg. Trotzdem danke für deine Info. Vielleicht migrieren die später auch die Daten der vorhanden Fahrzeuge in die My Cupra App. Wir warten mal ab.

**Comment by tillsteinbach** [comment]
Gibt es bei Seat auch eine Webseite wo dir dein Fahrzeug angezeigt wird? Bei VW ist das so: wenn du dein Fahrzeug (auch alt) in deinem Account hast, dann wird es in der ID-App angezeigt. Du kannst es aber nicht manuell in der App hinzufügen, es muss schon mit dem Account verknüpft sein.

Vielleicht schaffe ich es generell die Seat Anmeldung auch einzubauen ohne dass ich ein solches Auto besitze. Dann können wir schauen ob die alten Autos in der Schnittstelle wirklich fehlen, oder ob nur die App diese ausblendet.

**Comment by xerion3800** [comment]
Ja das gibt es in der Tat und zwar die "https://my.seat/" Cupra und Seat nutzen eine gemeinsame Plattform. Du kannst die ja mal https://github.com/Farfar/homeassistant-seatconnect anschauen damit funktioniert es heute schon vielleicht kannst du das ja einbinden.

**Comment by tillsteinbach** [comment]
Das benutzt die alte API die ich nicht mehr benutzen möchte.

**Comment by tillsteinbach** [comment]
Also der Login das geht schon, aber ohne Zugriff auf ein Fahrzeug komme ich da erstmal nicht weiter.

**Comment by xerion3800** [comment]
Ich kann dir für einen bestimmten Zeitraum Zugriff geben bräuchte dann Nur deine E-Mail Adresse und den Zeitraum wann du es nutzen möchtest.

**Comment by tillsteinbach** [comment]
Was wäre das für ein Fahrzeug?

Gerne ab sofort für maximal 5-6 Tage. Habe mir einen Seat account unter "Steinbach.till@gmx.de" angelegt.

**Comment by xerion3800** [comment]
Du solltest eine Einladung bekommen haben. Es geht um einen Cupra Formentor PHEV.

**Comment by tillsteinbach** [comment]
Einladung hab ich bekommen, aber irgendwie bleibt die Garage leer
<img width="1947" alt="Bildschirmfoto 2021-11-24 um 09 28 17" src="https://user-images.githubusercontent.com/3825852/143202063-b592e7ec-51fc-40b3-9e19-87e1d14fae6c.png">

**Comment by xerion3800** [comment]
Ich habe um 09:49 eine Mail bekommen das du als sekundärer Nutzer angemeldet wurdest.
![image](https://user-images.githubusercontent.com/46169403/143217758-f9a2b5ba-f0f2-42b1-8260-52bfbb4bab9f.png)

**Comment by tillsteinbach** [comment]
Ok, hab versucht über die neue API die Daten zu ziehen und es sieht so aus als seien die "alten" Fahrzeuge noch nicht eingepflegt. Ich muss erstmal jemanden finden der einen Cupar Born hat.

**Comment by xerion3800** [comment]
Okay also kann ich den Zugang wieder entfernen oder willst du noch was testen?

**Comment by tillsteinbach** [comment]
ne, kannst du erstmal wieder raus nehmen

**Comment by tillsteinbach** [comment]
Ich schließe mal hier weil wir mittlerweile einen User mit einem Cupar Born haben
