### ISSUE TITLE
Unknown attribute recurringOn and  Unknown attribute targetTimeLocal

### ISSUE THREAD

**Issue by gilder0** [tillsteinbach/WeConnect-python#172]
**Describe the bug**
It seems that VW API has changed and they return duplicated similar attributes to already existing ones.

**Logs**
domains/departureTimers/departureTimersStatus/timers/1/recurringTimer: Unknown attribute recurringOn with value {'mondays': True, 'tuesdays': True, 'wednesdays': True, 'thursdays': True, 'fridays': True, 'saturdays': True, 'sundays': True}
domains/departureTimers/departureTimersStatus/timers/1/recurringTimer: Unknown attribute targetTimeLocal with value 12:00

**Comment by tillsteinbach** [comment]
fixed in 0.60.4
