### ISSUE TITLE
Frequency of update() calls

### ISSUE THREAD

**Issue by HughMacdonald** [tillsteinbach/WeConnect-python#179]
I couldn't find anything in the docs about this, so I hope it's okay to have created an issue to ask the question.

I want to get an update to the plugConnectionStatus as soon as possible after plugging or unpluggging the car. My current understanding is that, to get an event, I need to call update(). Is there a maximum frequency of calling this that is considered okay by VW (and won't get my account blocked)?

Thanks

**Comment by HughMacdonald** [comment]
So after accidentally commenting a `sleep()` out of my code, and having it continuously calling `update()` until I caught it, it appears that it'll allow 5 or 6 in a minute before blocking you. However, this limit appears to reset every minute.

My code is currently updating every 2 minutes. I'd like to increase that to 1 minute or 30 seconds if at all possible, which I'll try once I'm confident in the stability of the current setup.

**Comment by HughMacdonald** [comment]
After running a couple of tests, it appears that this number is 7

**Comment by tillsteinbach** [comment]
I believe there is a total number of requests in 24h, but I could not figure out more.
