### ISSUE TITLE
Unsupported targetSOCreachable: reachable was provided, known values are [invalid, calculating, unknown] please report this as a bug.

### ISSUE THREAD

**Issue by rosscatley72** [tillsteinbach/WeConnect-python#182]
During an update() operation, the following error is encounted:

/vehicles/WVWZZZE1ZNP017424/domains/automation/chargingProfiles/nextChargingTimer/targetSOCreachable: TargetSOCReachable.UNKNOWN
/vehicles/WVWZZZE1ZNP017424/domains/automation/chargingProfiles/nextChargingTimer/targetSOCreachable: An unsupported targetSOCreachable: reachable was provided, known values are [invalid, calculating, unknown] please report this as a bug

Running on a Raspberry Pi, car is an ID.3.

def onWeConnectEvent(element, flags):
    """Simple callback example

    Args:
        element (AddressableObject): Object for which an event occured
        flags (AddressableLeaf.ObserverEvent): Information about the type of the event
    """
    match element.getLocalAddress():
        case "chargingState":
            writeEventToFile('**** CHARGING STATE UPDATE ****')
            print(element.getLocalAddress())
            match element.value:
                case ChargingStatus.ChargingState.NOT_READY_FOR_CHARGING:
                    writeEventToFile("Charging not ready")
                case ChargingStatus.ChargingState.READY_FOR_CHARGING:
                    writeEventToFile("Ready for Charging")
                case ChargingStatus.ChargingState.CHARGING:
                    writeEventToFile("Charging")
                case ChargingStatus.ChargingState.CHARGE_PURPOSE_REACHED_CONSERVATION:
                    writeEventToFile("Charge Purpose Reached Conservation")
        case "id":
            print("id - ignored")
        case "userDisablingAllowed":
            print("userDisablingAllowed - ignored")
        case "expirationDate":
            print("expirationDate - ignored")
        case _:
            #writeEventToFile(element.getLocalAddress())
            writeEventToFile(element.getGlobalAddress())
    

    try:

        if isinstance(element, addressable.AddressableAttribute):
            if flags & addressable.AddressableLeaf.ObserverEvent.VALUE_CHANGED:
                #writeEventToFile(f'Value changed: ,{element.getGlobalAddress()}: {element.value}')
                print(f'Value changed: ,{element.getGlobalAddress()}: {element.value}')
    except:
        print(datetime.now().strftime('%y-%m-%d %H:%M:%S')," Error Reported - Ignored")

**Expected behavior**
I'm not using targetSOCReachable in my API, but I noticed this as I am trying to understand how the API operates, and dump all events in the first instance to a log file, the expected behaviour would be not to see this error!

**Screenshots**

**Logs**
IF applicable logs that show the problem. Please take care to remove any confidential data from the logs (e.g. your vehicles VIN number, usernames or passwords)

 - OS: [e.g. Windows, Linux, MacOS, ...]
 - Version used [e.g. 0.6.2]

PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

**Additional context**
I'm fairly new to this - so please let me know what other information you need to let this be helpful!

**Comment by tillsteinbach** [comment]
Thank you for reporting, this is already fixed in master, will be part of next release.

**Comment by rosscatley72** [comment]
Excellent – thanks, and thanks for the library!

**Comment by tillsteinbach** [comment]
Released in 0.60.3
