### ISSUE TITLE
Unknown attribute temperatureOutsideStatus

### ISSUE THREAD

**Issue by Pyroil** [tillsteinbach/WeConnect-python#183]
After a software update to version 3.2 of my ID.4 I get the following error message:

/vehicles/WVXXXXXXXXXXXXXXX: Unknown attribute temperatureOutsideStatus with value {'error': {'message': 'Bad Gateway', 'errorTimeStamp': '2024-04-18T19:30:06Z', 'info': 'Upstream service responded with an unexpected status. If the problem persists, please contact our support.', 'code': 4007, 'group': 2, 'retry': True}} in domain measurements

I have version 0.60.2 installed on a Rpi
The error occurs during the weconnect.update() command

**Comment by tillsteinbach** [comment]
Released in 0.60.3
