### ISSUE TITLE
unsupported chargingScenario: immediatelyChargingFinished

### ISSUE THREAD

**Issue by t0bias-r** [tillsteinbach/WeConnect-python#203]
**Describe the bug**
An unsupported chargingScenario: `immediatelyChargingFinished` was provided, known values are [off, immediatelyChargingActive, errorChargingSystem, unknown charging scenario] **please report this as a bug**

**To Reproduce**
Start lastest version from main: f8a5ace5033fc47906232f00a3236c1d96702b02

**Expected behavior**
No crash

**Logs**

> WARNING:weconnect:[Mon Aug  5 13:44:50 2024] login
WARNING:weconnect:[Mon Aug  5 13:44:57 2024] login ok
INFO:weconnect:Clearing cache
WARNING:weconnect:[Mon Aug  5 13:44:57 2024] cache cleared
WARNING:weconnect:/vehicles/WVWZZZE1ZNP033417/domains/charging/chargingStatus/chargingScenario: **An unsupported chargingScenario: immediatelyChargingFinished was provided, known values are [off, immediatelyChargingActive, errorChargingSystem, unknown charging scenario] please report this as a bug**

**Comment by tillsteinbach** [comment]
Fixed in main, will be part of next release, thank you for reporting.
