### ISSUE TITLE
Testing climatization with my e-Up - unsupported devicePlatform

### ISSUE THREAD

**Issue by jual01** [tillsteinbach/WeConnect-python#27]
I just installed the code on my raspberry pi and first called "climatization" for my VW e-Up!

Login works but i got the message: unsupported devicePlatofrm

Code is running without any other errors but climatization doesn't work.

**Comment by tillsteinbach** [comment]
I would need some more logging output to understand the situation.

**Comment by jual01** [comment]
Thanks for the feedback. Now i tried to get some log-infos but there has not been any other infos.

I only get this warning:
WARNING:weconnect:An unsupported devicePlatform: MBB was provided, please report this as a bug

But surprise! It seems that VW has done some work on their Weconnect-Software over the weekend. After it couldn't be accessed last weekend now the script works. Now i am able to start/stop climatisation for my e-Up (with warning above).

So i am happy to find the first API that seems to work completly! Thanks a lot.

**Comment by tillsteinbach** [comment]
You are welcome! I reopen the bug to remind me to add MBB to the known plugins so you get rid of the warning in a future release.

**Comment by tillsteinbach** [comment]
Platform is now available in 0.29.0
