### ISSUE TITLE
control with -> climatization.py

### ISSUE THREAD

**Issue by tasisale** [tillsteinbach/WeConnect-python#30]
i test youtr climatization.py script to use, but the follow error i get.
` python3 climatization.py --username xxxxxxx --password xxxxxx --vin WVWZZZAUZLW91                                                                                                              6270
#  Initialize WeConnect
#  Login
#  update
/vehicles/WVWZZZAUZLW916270: Unknown attribute tags with value []
#  climatization status
ClimatizationState.OFF
#  start climatization
Traceback (most recent call last):
  File "climatization.py", line 42, in <module>
    main()
  File "climatization.py", line 37, in main
    vehicle.controls.climatizationControl.value = ControlOperation.START
  File "/home/fhemadmin/.local/lib/python3.8/site-packages/weconnect/addressable.py", line 334, in value
    self.setValueWithCarTime(newValue=newValue, lastUpdateFromCar=None)
  File "/home/fhemadmin/.local/lib/python3.8/site-packages/weconnect/addressable.py", line 230, in setValueWithCarTime
    self.notify(flags)
  File "/home/fhemadmin/.local/lib/python3.8/site-packages/weconnect/addressable.py", line 76, in notify
    observer(element=self, flags=flags)
  File "/home/fhemadmin/.local/lib/python3.8/site-packages/weconnect/elements/controls.py", line 86, in __onClimatizationContro                                                                                                              lChange
    raise SetterError(f'Could not control climatisation ({message})')
weconnect.errors.SetterError: Could not control climatisation (Resource could not be found - Internal error, please try again l                                                                                                              ater. If the problem persists, please contact our support. - Please retry in a moment)
`

**Comment by tasisale** [comment]
the same error i get by use:
`weconnect-cli --username xxxxxxxx --password xxxxxxxxx set /vehicles/WVWZZZAUZLW916270/controls/climatization start
id /vehicles/WVWZZZAUZLW916270/controls/climatization not found
`

**Comment by tasisale** [comment]
will use -> weconnect-cli 0.22.6 (using WeConnect-python 0.32.1)

**Comment by tillsteinbach** [comment]
It is "climatisation" not "climatization"

**Comment by tasisale** [comment]
> It is "climatisation" not "climatization"

sorry, don't work
`weconnect-cli --username simon@diehipps.de --password Maul%Dasch18! set /vehicles/WVWZZZAUZLW916270/controls/climatisation start
id /vehicles/WVWZZZAUZLW916270/controls/climatisation cannot be set: Could not control climatisation (Resource could not be found - Internal error, please try again later. If the problem persists, please contact our support. - Please retry in a moment)
`

**Comment by tillsteinbach** [comment]
Looks like VW is working on the servers. I also get that now.

**Comment by tasisale** [comment]
> Looks like VW is working on the servers. I also get that now.

i think so, will have a new WEConnect Client from VW.
When you think it will work again?

regards
simon

**Comment by tasisale** [comment]
Can you check again, the NEW app has not work tonight, now it works grait to climatisation, but the CLI and the MQTT can not start climatisation.
The same error as yesterday will show.
`weconnect-cli --username xxxxxxxx --password xxxxx set /vehicles/WVWZZZAUZLW916270/controls/climatisation start
id /vehicles/WVWZZZAUZLW916270/controls/climatisation cannot be set: Could not control climatisation (Resource could not be found - Internal error, please try again later. If the problem persists, please contact our support. - Please retry in a moment)
`

**Comment by tillsteinbach** [comment]
Can you control the climatization from the "We Connect ID" app?

**Comment by tasisale** [comment]
Yes, that works
![Foto 22-01-19 15-37-11 5562](https://user-images.githubusercontent.com/78930595/150156579-6c2515b8-3241-4fc8-a670-5be7a4b520d1.png)

**Comment by tillsteinbach** [comment]
This is not the "WeConnect ID" app (note the "ID"). This app uses the old API.

**Comment by tasisale** [comment]
> This is not the "WeConnect ID" app (note the "ID"). This app uses the old API.

ok, with the "ID" App i get an error.
I didn't know that the golf also works with the ID app, sorry :-)

**Comment by tillsteinbach** [comment]
No problem. I only support the new API introduced with the ID apps because that will be the future. Normally there is no problem with old cars, but it looks like since yesterday there is a problem.

**Comment by tasisale** [comment]
you have the same problem with new car?
we hope VW will not change the API so that "old" e-Cars will never control with the api, or?
you have contact with VW about this?

**Comment by tillsteinbach** [comment]
It worked until yesterday so I assume they will fix it soon. I have the same problem with an "old" car (Passat GTE)

**Comment by tasisale** [comment]
> It worked until yesterday so I assume they will fix it soon. I have the same problem with an "old" car (Passat GTE)

ok, so we wait, and drink coffee

**Comment by tasisale** [comment]
so i have news :-)!
have write emails with the "We Connect Support"
--
Um Ihnen schnellstmöglich eine Antwort zur Verfügung stellen zu können, sind wir mit der Fachabteilung im ständigen Austausch. Diese arbeitet bereits an einer Lösung.  
--
I also called, I was told that the API was probably no longer compatible with older non-ID cars, the "old" APP was still working!

regards
simon

**Comment by tillsteinbach** [comment]
It works again for me

**Comment by tasisale** [comment]
yes, it works, but the app`s (old and new(ID)) don't work at the moment for me.
we show whats VW will answerd about my ticket

**Comment by tasisale** [comment]
i have test to start the climatisation via CLI, it works at the moment, but again with 20,5 and not my set.
can you check, pls!?

**Comment by tillsteinbach** [comment]
20.5 is the fallback if there is no temperature set. I think the problem is that right now the temperature setting is gone in the settings

**Comment by tasisale** [comment]
> 20.5 is the fallback if there is no temperature set. I think the problem is that right now the temperature setting is gone in the settings

thats a perfect feature a fallback temperatur, thx.
will wait for the next test, for replay from vw.

**Comment by tasisale** [comment]
i get a error wile loding the targetTemperature_xxxx

`json2nameValueErrorText | error  parsing ''callback':  'https://mobileapi.apps.emea.vwapps.io/vehicles/callbacks/WVWZZZAUZLW916270/climatisation/settings',  'climatisationWithoutExternalPower': True, 'targetTemperature_K':  298.15'
json2nameValueInput | {'callback':   'https://mobileapi.apps.emea.vwapps.io/vehicles/callbacks/WVWZZZAUZLW916270/climatisation/settings',  'climatisationWithoutExternalPower': True, 'targetTemperature_K':  298.15}`

and the targetTemperature_C and targetTemperature_F necer be update and emtpy.
can you check this?
via CLI i get a value.

**Comment by tasisale** [comment]
news, via CLI i get now an error:
`get /vehicles/WVWZZZAUZLW916270/climatisation/climatisationSettings/targetTemperature_C
id /vehicles/WVWZZZAUZLW916270/climatisation/climatisationSettings/targetTemperature_C not found`

**Comment by tillsteinbach** [comment]
Is this still a problem?
