### ISSUE TITLE
Unknown attribute tags with value []

### ISSUE THREAD

**Issue by mitch-dc** [tillsteinbach/WeConnect-python#31]
Get this error message constant in the my terminal log. 

![image](https://user-images.githubusercontent.com/15835274/149994277-0f5f3a4c-7f69-47e1-b9f8-f6ed593fb624.png)

**Comment by tillsteinbach** [comment]
Yes, VW made changes to the interface. It's already added n master and will be included in the next release

**Comment by mitch-dc** [comment]
Hmm cool, what purpose do you think the "tags" wil have?

**Comment by tillsteinbach** [comment]
I have no idea :)

**Comment by tillsteinbach** [comment]
0.33.0 is released adding the unknown tags value
