### ISSUE TITLE
unknown Charge mode 

### ISSUE THREAD

**Issue by gertparisis** [tillsteinbach/WeConnect-python#4]
**Describe the bug**
after I Login, and do an update I get this error
An unsupported chargeMode: off was provided, please report this as a bug

**To Reproduce**
w=weconnect.WeConnect(username='xxxx@xxxx.xx',password='xxxxxx',updateAfterLogin=False, loginOnInit=False)
w.login()
w.update()
An unsupported chargeMode: off was provided, please report this as a bug

 - OS: MacosX
 car : id4

**Comment by tillsteinbach** [comment]
Thanks for reporting, will do a bugfix release soon

**Comment by tillsteinbach** [comment]
Version 0.9.1 now should contain the missing chargeMode 'off'
