### ISSUE TITLE
Error when setting maxChargeCurrentAC

### ISSUE THREAD

**Issue by mitch-dc** [tillsteinbach/WeConnect-python#43]
I get an error when i want to switch maxChargeCurrentAC from maximum to reduced or other way around.
The app does work. 

`Failed to send request to car - issubclass() arg 1 must be a class`

**Comment by tillsteinbach** [comment]
Is that on 0.37.0 or 0.37.1?

**Comment by mitch-dc** [comment]
Tried it with 0.37.2 and it's fixed!
