### ISSUE TITLE
Incorrect range - from source

### ISSUE THREAD

**Issue by ColinRobbins** [tillsteinbach/WeConnect-python#66]
**Describe the bug**
In some ciscumstances the API is reporting an incorrect milage for the EV.

I recognise this is an issue with the upstream source data supplied, and not an issue with the API.

My reason for reporting is to try see of only I am seeing the issue, or if it is general.   If general, pointers on how to report to the VW team would be good.

**To Reproduce**
When the EV is driving or charging the range is both kM and Miles is correctly reported.

Sometimes, then the car is parked up, the range is incorrectly reported in both kM and Miles
It turns out the errors is a factor of 0.62, it seems coincidental this is the conversion factor for miles to km.
(This has the effect that the kM attribute actually shows the number of miles range).

So, it seems to me something upsteams has an error in its range conversion.

**Expected behavior**
Miles to show miles, and kM to show kM!!!

**Screenshots**
N/A

**Logs**
N/A

**Additional context**
The discrepancy shows up in the weCOnnectID app as well, so confirming an upstream issue.

Sorry if it is considered inapproproiate to seek assistance here - please just close the issue.  But pointers on where to report it would be appreciated

**Comment by tillsteinbach** [comment]
If you see the problem in the WeConnect App too I would report that to VW directly.
Do you think there is a way to reliably detect the miscalculation? In that case I could fix that in the API.

**Comment by ColinRobbins** [comment]
Thanks.   Do you know how to report to VW?

I was able to correct the miscalculation when the “car is active” value was available.  But not found a way now this is removed.
Something like…
```
If car_is_charging or car_is_active:
   Use value
Else
   Ignore value, use previous.
```

**Comment by tillsteinbach** [comment]
Yes, I also miss the isActive flag. Hope something similar will come back.

**Comment by tillsteinbach** [comment]
isActive flag will be back with 0.45.1

**Comment by ColinRobbins** [comment]
I reported the incorrect range issue to VW in July.  After supplying sufficient evidence the error was thier end, they now claim to have fixed this issue.
Thus closing the report here.
