### ISSUE TITLE
Clarification: does locking/unlocking with the library work for id.3?

### ISSUE THREAD

**Issue by pplucky** [tillsteinbach/WeConnect-python#82]
Hello.

Can anyone clarify if locking/unlocking added in [0.47.0](https://github.com/tillsteinbach/WeConnect-python/releases/tag/v0.47.0) works for an id.3?

My question comes because this is not currently supported by the We Connect ID app and it would be awesome if possible (I have reported this to VW, as this works for other PHEV VW models (not EV), using a different app...

Thanks for clarifying.

**Comment by tillsteinbach** [comment]
There is an API endpoint, but until now it just throws an error

**Comment by pplucky** [comment]
> There is an API endpoint, but until now it just throws an error

Great, thanks for clarifying. There is hope to get this in the future, at least ;-).

**Comment by hovant** [comment]
> There is an API endpoint, but until now it just throws an error

How do you know that there is API endpoint? What is it? Do you have some spec about available API endpoints?

**Comment by tillsteinbach** [comment]
It is already implemented in the library (see https://github.com/tillsteinbach/WeConnect-python/blob/main/weconnect/elements/controls.py#L218). There is no public spec. It is all analysis of what is already there.
