### ISSUE TITLE
Clarification: does the library provide any alarm information for id.3?

### ISSUE THREAD

**Issue by pplucky** [tillsteinbach/WeConnect-python#86]
Hello.

Can anyone clarify if the library provides/is able to provide any alarm information for an id.3?

I was surprised to know that even though the alarm of my connected car may be triggered, no notification is sent from the We Connect ID app (not sure if it is only lacking the notification).

Thanks for clarifying.

**Comment by tillsteinbach** [comment]
No, the API does not provide that yet.
