### ISSUE TITLE
Support for ID Buzz

### ISSUE THREAD

**Issue by mitch-dc** [tillsteinbach/WeConnect-python#94]
I've got 2 requests to add support for the ID Buzz in the Home Assistant integration based on this library. 
https://community.home-assistant.io/t/custom-integration-volkswagen-weconnect-id-europe/380933/99

Can you take a look if it's possible to add this? 

`[weconnect] /vehicles/12345/brandCode: An unsupported brandCode: N was provided, known values are [V, unknown brand code] `

**Comment by tillsteinbach** [comment]
yes sure!

**Comment by tillsteinbach** [comment]
I released 0.51.0. Can you check if everything still works for you?
